services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: appimage
    depends_on:
      - 'postgres'
      - 'redis'
    ports:
      - '3000:3000'
    command: bash start
    volumes:
      - '.:/petshop_admin'
    volumes_from:
      - box
    env_file: .env

  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    container_name: ${DATABASE_HOST}
    ports:
      - "6543:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'app'
    build: .
    command: bash start_jobs
    volumes:
      - '.:/petshop_admin'
    volumes_from:
      - box


  box:
    image: busybox
    volumes:
      - /box

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1025:25
      - 1080:80

volumes:
  redis:
  postgres:
  box:
