default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  # username: <%= ENV['DATABASE_USER'] %>
  user: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  # timeout: 5000
  # url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
