default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  timeout: 5000
  # url: <%= ENV['POSTGRES_URL'] %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  

test:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
