default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] || '5432' %>
  # username: <%= ENV['PGUSER'] %>
  user: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  # timeout: 5000
  # url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: <%= ENV['PGDATABASE'] %>
  

test:
  <<: *default
  database: <%= ENV['PGDATABASE'] %>

production:
  <<: *default
  database: <%= ENV['PGDATABASE'] %>
